/**
 * Microservices E-commerce Architecture
 */

import type { ArchitectureDefinition } from '../../types';

export const microservicesEcommerceArchitecture: ArchitectureDefinition = {
  id: 'microservices-ecommerce',
  name: 'Microservices E-commerce Platform',
  description: 'High-availability containerized architecture',
  category: 'microservices',
  tags: ['ecs', 'fargate', 'aurora', 'elasticache', 'alb', 'cloudfront'],
  version: '1.0.0',
  canvas: {
    width: 1000,
    height: 600,
  },
  services: [
    {
      id: 'route53',
      type: 'route53',
      label: 'Route 53',
      position: { x: 50, y: 250 },
      badge: 'DNS',
      description: 'DNS routing and domain management',
    },
    {
      id: 'cloudfront',
      type: 'cloudfront',
      label: 'CloudFront',
      position: { x: 180, y: 250 },
      description: 'CDN for static content and API caching',
    },
    {
      id: 'alb',
      type: 'alb',
      label: 'Application LB',
      position: { x: 340, y: 250 },
      description: 'Application Load Balancer for traffic distribution',
    },
    {
      id: 'user-service',
      type: 'ecs',
      label: 'User Service',
      position: { x: 520, y: 100 },
      description: 'Handles user authentication and profiles',
    },
    {
      id: 'order-service',
      type: 'ecs',
      label: 'Order Service',
      position: { x: 520, y: 250 },
      description: 'Order processing and management',
    },
    {
      id: 'inventory-service',
      type: 'ecs',
      label: 'Inventory Service',
      position: { x: 520, y: 400 },
      description: 'Inventory tracking and stock management',
    },
    {
      id: 'aurora',
      type: 'aurora',
      label: 'Aurora PostgreSQL',
      position: { x: 700, y: 170 },
      description: 'Primary database with Multi-AZ deployment',
    },
    {
      id: 'elasticache',
      type: 'elasticache',
      label: 'Redis Cache',
      position: { x: 700, y: 330 },
      badge: 'Cache',
      description: 'In-memory cache for session and data caching',
    },
    {
      id: 's3',
      type: 's3',
      label: 'Product Images',
      position: { x: 860, y: 100 },
      description: 'S3 bucket for static assets and images',
    },
    {
      id: 'cloudwatch',
      type: 'cloudwatch',
      label: 'CloudWatch',
      position: { x: 860, y: 250 },
      description: 'Monitoring, logging, and alerting',
    },
  ],
  connections: [
    {
      id: 'flow-r53-cf',
      from: 'route53',
      to: 'cloudfront',
      type: 'sync',
      label: 'DNS',
      sequence: 1,
    },
    {
      id: 'flow-cf-alb',
      from: 'cloudfront',
      to: 'alb',
      type: 'sync',
      sequence: 2,
    },
    {
      id: 'flow-cf-s3',
      from: 'cloudfront',
      to: 's3',
      type: 'sync',
      label: 'Static',
      sequence: 2,
    },
    {
      id: 'flow-alb-user',
      from: 'alb',
      to: 'user-service',
      type: 'sync',
      sequence: 3,
    },
    {
      id: 'flow-alb-order',
      from: 'alb',
      to: 'order-service',
      type: 'sync',
      sequence: 3,
    },
    {
      id: 'flow-alb-inv',
      from: 'alb',
      to: 'inventory-service',
      type: 'sync',
      sequence: 3,
    },
    {
      id: 'flow-user-aurora',
      from: 'user-service',
      to: 'aurora',
      type: 'sync',
      sequence: 4,
    },
    {
      id: 'flow-order-aurora',
      from: 'order-service',
      to: 'aurora',
      type: 'sync',
      sequence: 4,
    },
    {
      id: 'flow-order-cache',
      from: 'order-service',
      to: 'elasticache',
      type: 'sync',
      label: 'Cache',
      sequence: 4,
    },
    {
      id: 'flow-inv-cache',
      from: 'inventory-service',
      to: 'elasticache',
      type: 'sync',
      sequence: 4,
    },
  ],
  groups: [
    {
      id: 'vpc',
      label: 'VPC',
      serviceIds: ['alb', 'user-service', 'order-service', 'inventory-service', 'aurora', 'elasticache'],
      style: 'vpc',
      color: '#A166FF',
    },
  ],
  legend: [
    { type: 'sync', label: 'Sync Request' },
  ],
};
