/**
 * Serverless Payment Processing Architecture
 */

import type { ArchitectureDefinition } from '../../types';

export const serverlessPaymentArchitecture: ArchitectureDefinition = {
  id: 'serverless-payment',
  name: 'Serverless Payment Processing',
  description: 'Real-time payment validation with async settlement',
  category: 'serverless',
  tags: ['payment', 'lambda', 'api-gateway', 'dynamodb', 'sqs', 'sns'],
  version: '1.0.0',
  canvas: {
    width: 1000,
    height: 550,
  },
  services: [
    {
      id: 'waf',
      type: 'waf',
      label: 'WAF',
      position: { x: 50, y: 220 },
      description: 'Web Application Firewall - protects against common web exploits',
    },
    {
      id: 'api-gateway',
      type: 'api-gateway',
      label: 'API Gateway',
      position: { x: 180, y: 220 },
      badge: 'HTTPS',
      description: 'REST API endpoint for payment requests',
    },
    {
      id: 'cognito',
      type: 'cognito',
      label: 'Cognito',
      position: { x: 180, y: 80 },
      description: 'User authentication and authorization',
    },
    {
      id: 'lambda-auth',
      type: 'lambda',
      label: 'Authorizer',
      position: { x: 310, y: 120 },
      badge: 'JWT',
      description: 'Lambda authorizer for API Gateway',
    },
    {
      id: 'lambda-handler',
      type: 'lambda',
      label: 'Payment Handler',
      position: { x: 440, y: 220 },
      description: 'Processes payment requests and validates transactions',
    },
    {
      id: 'dynamodb',
      type: 'dynamodb',
      label: 'Transactions',
      position: { x: 600, y: 220 },
      description: 'Stores transaction records',
    },
    {
      id: 'sqs',
      type: 'sqs',
      label: 'Settlement Queue',
      position: { x: 440, y: 380 },
      description: 'FIFO queue for async settlement processing',
    },
    {
      id: 'lambda-worker',
      type: 'lambda',
      label: 'Settlement Worker',
      position: { x: 600, y: 380 },
      badge: 'Poll',
      description: 'Processes settlement jobs from queue',
    },
    {
      id: 'sns',
      type: 'sns',
      label: 'Notifications',
      position: { x: 760, y: 380 },
      description: 'Sends payment notifications to subscribers',
    },
    {
      id: 'cloudwatch',
      type: 'cloudwatch',
      label: 'Monitoring',
      position: { x: 800, y: 220 },
      description: 'Metrics, logs, and alarms',
    },
  ],
  connections: [
    {
      id: 'flow-waf-api',
      from: 'waf',
      to: 'api-gateway',
      type: 'sync',
      label: 'HTTPS',
      sequence: 1,
    },
    {
      id: 'flow-cognito-auth',
      from: 'cognito',
      to: 'lambda-auth',
      type: 'sync',
      label: 'JWT',
      sequence: 2,
    },
    {
      id: 'flow-api-auth',
      from: 'api-gateway',
      to: 'lambda-auth',
      type: 'sync',
      sequence: 2,
    },
    {
      id: 'flow-api-handler',
      from: 'api-gateway',
      to: 'lambda-handler',
      type: 'sync',
      sequence: 3,
    },
    {
      id: 'flow-handler-dynamo',
      from: 'lambda-handler',
      to: 'dynamodb',
      type: 'sync',
      sequence: 4,
    },
    {
      id: 'flow-handler-sqs',
      from: 'lambda-handler',
      to: 'sqs',
      type: 'async',
      sequence: 5,
    },
    {
      id: 'flow-sqs-worker',
      from: 'sqs',
      to: 'lambda-worker',
      type: 'async',
      label: 'Poll',
      sequence: 5,
    },
    {
      id: 'flow-worker-dynamo',
      from: 'lambda-worker',
      to: 'dynamodb',
      type: 'sync',
      sequence: 6,
    },
    {
      id: 'flow-worker-sns',
      from: 'lambda-worker',
      to: 'sns',
      type: 'async',
      sequence: 6,
    },
    {
      id: 'flow-handler-cw',
      from: 'lambda-handler',
      to: 'cloudwatch',
      type: 'stream',
      sequence: 4,
    },
  ],
  legend: [
    { type: 'sync', label: 'Sync Request' },
    { type: 'async', label: 'Async Event' },
    { type: 'stream', label: 'Stream' },
  ],
};
